import { createHash } from "node:crypto";
import type {
  Diagnostic,
  ElevationProviderId,
  ElevationSnapshot,
  Wgs84Bounds,
} from "@osm3d/contracts";
import { boundsCenter, wgs84ToLocal } from "@osm3d/geo";
import { z } from "zod";
import type { AppConfig } from "./config.js";

export interface ElevationProvider {
  readonly id: ElevationProviderId;
  fetch(bounds: Wgs84Bounds): Promise<ElevationSnapshot>;
}

interface GridDimensions {
  columns: number;
  rows: number;
  eastWestMeters: number;
  northSouthMeters: number;
}

const UsgsSampleSchema = z.object({
  locationId: z.number().int().nonnegative(),
  value: z.string(),
  resolution: z.number().optional(),
  attributes: z
    .object({
      VerticalDatum: z.string().nullish(),
      ProductName: z.string().nullish(),
    })
    .optional(),
});

const UsgsResponseSchema = z.object({
  samples: z.array(UsgsSampleSchema).optional(),
  error: z
    .object({ message: z.string(), details: z.array(z.string()).optional() })
    .optional(),
});

const usgsAttribution = {
  text: "USGS The National Map 3D Elevation Program (3DEP)",
  url: "https://www.usgs.gov/3d-elevation-program",
  license: "Public domain",
} as const;

const fixtureAttribution = {
  text: "Synthetic elevation fixture generated by StreetRove",
  url: "https://github.com/nkimber/OpenStreetMapTo3D",
  license: "MIT",
} as const;

function dimensionsFor(
  bounds: Wgs84Bounds,
  targetSpacingMeters: number,
  maxDimension: number,
): GridDimensions {
  const anchor = boundsCenter(bounds);
  const southwest = wgs84ToLocal(
    { longitude: bounds.west, latitude: bounds.south, height: 0 },
    anchor,
  );
  const northeast = wgs84ToLocal(
    { longitude: bounds.east, latitude: bounds.north, height: 0 },
    anchor,
  );
  const eastWestMeters = Math.abs(northeast.east - southwest.east);
  const northSouthMeters = Math.abs(northeast.north - southwest.north);
  return {
    columns: Math.min(
      maxDimension,
      Math.max(2, Math.ceil(eastWestMeters / targetSpacingMeters) + 1),
    ),
    rows: Math.min(
      maxDimension,
      Math.max(2, Math.ceil(northSouthMeters / targetSpacingMeters) + 1),
    ),
    eastWestMeters,
    northSouthMeters,
  };
}

function snapshotFromGrid(input: {
  provider: ElevationProviderId;
  dataset: string;
  bounds: Wgs84Bounds;
  dimensions: GridDimensions;
  heights: number[];
  verticalDatum: string;
  attribution: ElevationSnapshot["attribution"];
}): ElevationSnapshot {
  const roundedHeights = input.heights.map((height) =>
    Number(height.toFixed(3)),
  );
  const minHeight = Math.min(...roundedHeights);
  const maxHeight = Math.max(...roundedHeights);
  const contentHash = createHash("sha256")
    .update(
      JSON.stringify({
        schemaVersion: 1,
        provider: input.provider,
        dataset: input.dataset,
        bounds: input.bounds,
        columns: input.dimensions.columns,
        rows: input.dimensions.rows,
        heights: roundedHeights,
        verticalDatum: input.verticalDatum,
      }),
    )
    .digest("hex");
  return {
    schemaVersion: 1,
    provider: input.provider,
    dataset: input.dataset,
    retrievedAt: new Date().toISOString(),
    bounds: input.bounds,
    columns: input.dimensions.columns,
    rows: input.dimensions.rows,
    spacingMeters: {
      eastWest:
        input.dimensions.eastWestMeters / (input.dimensions.columns - 1),
      northSouth:
        input.dimensions.northSouthMeters / (input.dimensions.rows - 1),
    },
    heights: roundedHeights,
    verticalDatum: input.verticalDatum,
    units: "meters",
    minHeight,
    maxHeight,
    contentHash,
    attribution: input.attribution,
  };
}

function gridPoints(
  bounds: Wgs84Bounds,
  columns: number,
  rows: number,
): [number, number][] {
  const points: [number, number][] = [];
  for (let row = 0; row < rows; row += 1) {
    const latitude =
      bounds.south + ((bounds.north - bounds.south) * row) / (rows - 1);
    for (let column = 0; column < columns; column += 1) {
      const longitude =
        bounds.west + ((bounds.east - bounds.west) * column) / (columns - 1);
      points.push([longitude, latitude]);
    }
  }
  return points;
}

function fillNoData(heights: number[]): number[] {
  const result = [...heights];
  const valid = result.filter(Number.isFinite);
  if (valid.length === 0)
    throw new Error("The elevation source returned no data.");
  const fallback =
    valid.reduce((sum, height) => sum + height, 0) / valid.length;
  let previous = fallback;
  for (let index = 0; index < result.length; index += 1) {
    if (Number.isFinite(result[index])) previous = result[index] ?? previous;
    else result[index] = previous;
  }
  previous = fallback;
  for (let index = result.length - 1; index >= 0; index -= 1) {
    if (Number.isFinite(result[index])) previous = result[index] ?? previous;
    else result[index] = previous;
  }
  return result;
}

export class Usgs3depElevationProvider implements ElevationProvider {
  readonly id = "usgs-3dep" as const;

  constructor(
    private readonly config: AppConfig,
    private readonly fetchImplementation: typeof fetch = fetch,
  ) {}

  async fetch(bounds: Wgs84Bounds): Promise<ElevationSnapshot> {
    const dimensions = dimensionsFor(
      bounds,
      this.config.ELEVATION_SAMPLE_SPACING_METERS,
      this.config.ELEVATION_MAX_GRID_DIMENSION,
    );
    const points = gridPoints(bounds, dimensions.columns, dimensions.rows);
    const heights = Array<number>(points.length).fill(Number.NaN);
    let verticalDatum = "North American Vertical Datum of 1988 (NAVD 88)";
    let dataset = "USGS 3DEP Bare Earth DEM";
    const batches: { offset: number; points: [number, number][] }[] = [];
    for (
      let offset = 0;
      offset < points.length;
      offset += this.config.ELEVATION_SAMPLE_BATCH_SIZE
    ) {
      batches.push({
        offset,
        points: points.slice(
          offset,
          offset + this.config.ELEVATION_SAMPLE_BATCH_SIZE,
        ),
      });
    }

    for (let start = 0; start < batches.length; start += 4) {
      const group = batches.slice(start, start + 4);
      await Promise.all(
        group.map(async (batch) => {
          const body = new URLSearchParams({
            geometryType: "esriGeometryMultipoint",
            geometry: JSON.stringify({
              points: batch.points,
              spatialReference: { wkid: 4326 },
            }),
            returnFirstValueOnly: "true",
            interpolation: "RSP_BilinearInterpolation",
            outFields: "VerticalDatum,ProductName",
            f: "json",
          });
          const response = await this.fetchImplementation(
            this.config.USGS_ELEVATION_BASE_URL,
            {
              method: "POST",
              headers: {
                Accept: "application/json",
                "Content-Type":
                  "application/x-www-form-urlencoded;charset=UTF-8",
                "User-Agent": this.config.OSM_USER_AGENT,
              },
              body,
              signal: AbortSignal.timeout(45_000),
            },
          );
          if (!response.ok)
            throw new Error(`USGS 3DEP returned HTTP ${response.status}.`);
          const parsed = UsgsResponseSchema.parse(await response.json());
          if (parsed.error) throw new Error(parsed.error.message);
          for (const sample of parsed.samples ?? []) {
            const value = Number(sample.value.split(",")[0]);
            const targetIndex = batch.offset + sample.locationId;
            if (Number.isFinite(value) && targetIndex < heights.length)
              heights[targetIndex] = value;
            verticalDatum = sample.attributes?.VerticalDatum ?? verticalDatum;
            dataset = sample.attributes?.ProductName ?? dataset;
          }
        }),
      );
    }

    const missing = heights.filter((height) => !Number.isFinite(height)).length;
    if (missing / heights.length > 0.25) {
      throw new Error(
        `USGS 3DEP has insufficient coverage for this area (${missing} missing samples).`,
      );
    }
    return snapshotFromGrid({
      provider: this.id,
      dataset,
      bounds,
      dimensions,
      heights: fillNoData(heights),
      verticalDatum,
      attribution: usgsAttribution,
    });
  }
}

export function createFixtureElevation(bounds: Wgs84Bounds): ElevationSnapshot {
  const dimensions = dimensionsFor(bounds, 24, 49);
  const heights: number[] = [];
  for (let row = 0; row < dimensions.rows; row += 1) {
    const north = row / (dimensions.rows - 1);
    for (let column = 0; column < dimensions.columns; column += 1) {
      const east = column / (dimensions.columns - 1);
      const hill =
        7 * Math.exp(-((east - 0.72) ** 2 + (north - 0.7) ** 2) / 0.035);
      heights.push(82 + north * 22 + east * 4 + hill);
    }
  }
  return snapshotFromGrid({
    provider: "fixture",
    dataset: "Deterministic neighborhood slope fixture",
    bounds,
    dimensions,
    heights,
    verticalDatum: "Synthetic local datum",
    attribution: fixtureAttribution,
  });
}

export function createFlatFallbackElevation(
  bounds: Wgs84Bounds,
): ElevationSnapshot {
  return snapshotFromGrid({
    provider: "flat-fallback",
    dataset: "Flat fallback (no DEM coverage)",
    bounds,
    dimensions: dimensionsFor(bounds, 10_000, 2),
    heights: [0, 0, 0, 0],
    verticalDatum: "Not applicable",
    attribution: {
      text: "No elevation dataset available; flat terrain fallback",
      url: "https://github.com/nkimber/OpenStreetMapTo3D",
      license: "N/A",
    },
  });
}

export async function fetchElevationData(
  osmProvider: "overpass" | "fixture",
  bounds: Wgs84Bounds,
  config: AppConfig,
): Promise<{ snapshot: ElevationSnapshot; diagnostics: Diagnostic[] }> {
  if (osmProvider === "fixture") {
    return { snapshot: createFixtureElevation(bounds), diagnostics: [] };
  }
  try {
    return {
      snapshot: await new Usgs3depElevationProvider(config).fetch(bounds),
      diagnostics: [],
    };
  } catch (error) {
    const reason = error instanceof Error ? error.message : "Unknown DEM error";
    return {
      snapshot: createFlatFallbackElevation(bounds),
      diagnostics: [
        {
          code: "elevation.flat-fallback",
          severity: "warning",
          message: `Live elevation could not be loaded; this snapshot uses flat terrain. ${reason}`,
        },
      ],
    };
  }
}
